#!/bin/sh

. "$(git --exec-path)/git-sh-setup"

GIT_WORKING_TREE="$(git rev-parse --show-toplevel)"

printf "** Updating user.js ...\n"
yes Y | "${GIT_WORKING_TREE}/updater.sh"

printf "** Cleaning prefs.js ...\n"
yes 1 | "${GIT_WORKING_TREE}/prefsCleaner.sh"